name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: install JUnit
      run: sudo apt install junit4

    - name: build files
      run: javac -cp .:/usr/share/java/junit4.jar PrimeCheck.java PrimeCheckTest.java

    - name: run tests
      run: java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore PrimeCheckTest